### ISSUE TITLE
 Weekly Scrum - Mar 1, 2023

### ISSUE THREAD

**Issue by Brandon-999** [Brandon-999/4806_project#26]

**Comment by Brandon-999** [comment]
This past week I have been working on the front end.
There are 4 pages now (Home, Book, Login, Register);
The pages currently interface with bare-bones stubs in the back-end.

Next week I will continue integrating the front end with the back-end provided by other group members.

I am blocked by an error that prevents the app from running.
See this issue: https://github.com/Brandon-999/4806_project/issues/25

**Comment by Mohman556** [comment]
Over the week, I've worked on Implementing the View and Model Controllers for the pages and Objects within the system.
I will continue to make progress on the controllers over the week and keep my partners updated.

**Comment by khalidkanaan** [comment]
This week I've worked on the UserModel & UserRepository, as well as OrderModel & OrderRepository. The PRs have been merged, I might add some additional helper functions to OrderRepository as the project progresses. Next week I will be working on implementing ShoppingCartModel and ShoppingCartRepository.
Nothing is currently holding me back

**Comment by KareemEH** [comment]
This week I've completed The BookModel and BookRepository classes, I also assisted in completing the UserModel & UserRepository as well as the necessary service layers. No open PRs atm. Working on resolcing the ongoing build issue. Next week I plan on completing the service layer funcitonality required for the front end (Hopefully after the build error is resolved).
Nothing is currently holding me back.

**Comment by evan-lloyd-git** [comment]
This week I've worked on the User Service. The service contains methods to update and retrieve information from the user repository. I ran into some issues with testing and integration that I am working on resolving now. Next week I plan to complete the user service implementation and finish testing the classes.
