### ISSUE TITLE
Weekly scrum - Feb 22, 2023

### ISSUE THREAD

**Issue by Brandon-999** [Brandon-999/4806_project#5]

**Comment by Brandon-999** [comment]
I will work on the front-end views for the homepage and book views.
Nothing is currently holding me back.

**Comment by khalidkanaan** [comment]
This week I've worked on the UserModel & UserRepository, as well as OrderModel & OrderRepository. The PRs have been merged, I might add some additional helper functions to OrderRepository as the project progresses. Next week I will be working on implementing ShoppingCartModel and ShoppingCartRepository.
Nothing is currently holding me back

**Comment by KareemEH** [comment]
This week I created the file structure for the project. This structure includes how the packages are distributed according to the MVC architecture we are following. I also began work on implementing the BookModel and BookRepository classes. Next week I plan on finishing BookModel and BookRepository. Nothing is currently holding me back.
